version: '3'  

services:
  db:
    image: postgres:15.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_USER_PWD}
    container_name: blogDB
    volumes:
      - ./postgres:/var/lib/postgresql/data